baseURL = "https://nasiricarpet.ir/"
languageCode = "fa-ir"
title = "وب سایت اختصاصی دکتر محمدرضا نصیری"
languageDir = "rtl"  # این دستور، پوسته PaperMod را کاملاً راست‌چین می‌کند

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  # این فایل CSS، فونت ما را اضافه خواهد کرد
  custom_css = ["css/custom.css"]

# این همان منویی است که شما درخواست کردید
[menu]
  [[menu.main]]
    identifier = "profile"
    name = "پروفایل من"
    url = "/profile/"
    weight = 10
  [[menu.main]]
    identifier = "articles"
    name = "مقالات"
    url = "/articles/"
    weight = 20
  [[menu.main]]
    identifier = "services"
    name = "خدمات"
    url = "/services/"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "ارتباط با من"
    url = "/contact/"
    weight = 40	
	[params.profileMode]
  enabled = true
  title = "دکتر محمدرضا نصیری"
  subtitle = "کارشناس رسمی دادگستری در رشته فرش | مشاوره در خرید و فروش فرش دستباف"
  imageUrl = "/images/profile.jpg" # آدرس عکس پروفایل شما
  imageWidth = 200 # عرض عکس
  imageHeight = 200 # ارتفاع عکس
  imageTitle = "عکس پروفایل دکتر نصیری"